name: Run Tests

on: 
  push:
    branches:
      - main
      - 'qcflow-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
      - name: Create and activate environment
        run: |
          conda config --add channels defaults
          conda config --add channels conda-forge
          conda config --add channels anaconda
          conda env create -f QCflow.yml
          conda activate QCflow
      - name: Run Tests
        run: python -m pytest -v QCflow/tests/
